apiVersion: apps/v1
kind: Deployment
metadata:
  name: outerlyy-user-service
  labels:
    app: outerlyy-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outerlyy-user-service
  template:
    metadata:
      labels:
        app: outerlyy-user-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:docker-image-version
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: outerlyy-user-service
  labels:
    app: outerlyy-user-service
spec:
  selector:
    app: outerlyy-user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80