---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: outerlyy-user
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: outerlyy-user
  targetCPUUtilizationPercentage: 80
